on:
  workflow_dispatch:
  push:
    branches: ["main","dev"]

jobs:
  build:
    environment: main
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.set_latest_tag.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Install musl cc
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools musl-dev musl
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache: false
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          release_branches: main
          tag_prefix: v
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/opengovern.insteadOf https://github.com/opengovern
      - name: Build azuread plugin app
        working-directory: ./steampipe-plugin-azuread
        run: make build
      - name: Pack azuread plugin build
        working-directory: ./steampipe-plugin-azuread
        run: |
          tar -cvf build.tar build
      - name: Upload azuread plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-azuread
          path: ./steampipe-plugin-azuread/build.tar
          retention-days: 1
      - name: Build local describer app
        working-directory: .
        run: make local-build
      - name: Pack local describer build
        working-directory: .
        run: |
          tar -cvf local.tar local
      - name: Upload local artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-og-describer-entraid
          path: ./local.tar
          retention-days: 1
      - name: Set latest tag output
        id: set_latest_tag
        run: |
          if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
            echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          fi
  deploy-azuread-plugin:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download azuread plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-azuread
          path: .
      - name: Unpack artifact
        run: |
          tar -xvf build.tar
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/steampipe-plugin-azuread:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-azuread/docker/Dockerfile
          context: .
  deploy-local-describer:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: local-og-azure-describer
          path: .
      - name: Unpack plugin artifact
        run: |
          tar -xvf local.tar
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/og-describer-entraid:local-${{ needs.build.outputs.latest_tag }}
          file: DockerFileLocal
          context: .